# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_DRM_DEBUG_SELFTEST) += test-drm_mm.o test-drm_cmdline_parser.o \
				    test-drm_format.o test-drm_framebuffer.o \
				    test-drm_rect.o test-drm_dp_mst_helper.o \
				    test-drm_damage_helper.o test-drm_plane_helper.o

obj-$(CONFIG_DRM_PLANE_HELPER_KUNIT_TEST) += test-drm_format.o
